import { AppSidebar } from "@/components/app-sidebar";
import {
  Sidebar,
  SidebarInset,
  SidebarProvider,
} from "@/components/ui/sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <Sidebar variant="inset">
        <AppSidebar />
      </Sidebar>
      <SidebarInset className="overflow-hidden">
        <main className="flex-1">{children}</main>
      </SidebarInset>
    </SidebarProvider>
  );
}
